### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by jeremydeanw** [adamcogen/drum-machine-py-poc#1]
Hi there, this looks really sweet. On a PC, so i'm not sure how to test.  
Have you checked out: https://github.com/tiburzi/cync  or cync.app ?  
I'm wondering if there is a way to output live midi from it. (to trigger a hardware drum machine) It already has a midi save function. I have no formal coding experience.   
Just trying to find someone to help me figure it out.  Do you have any experience with javascript? 
-Jeremy

**Comment by adamcogen** [comment]
Hi Jeremy, 
Wow, this is so cool! I’m not sure about outputting live midi from Javascript, but I will try to look into this soon. The Cync UI design also gives me a few ideas for features that I think would be cool to add. I don’t have much experience with JS but I’ll see if I can pick it up. 
Adam

**Comment by adamcogen** [comment]
Also, it’s untested but I think the drum machine I made should be able work on Windows, as long as you have Python 3 installed and a midi device / port for it to connect to. For connecting to a DAW, I’m sure there’s a way to set up a virtual midi port on Windows.

**Comment by jeremydeanw** [comment]
Ok cool thanks, I'll see if I can get it going. I like how simple and user friendly it looks....all the polyrhythmic drum machines I see here on github are so complicated looking and fussy.  
I dig the circular idea of cync, somehow it just works for my brain.  
That would be so so cool. I did ask the guys who wrote it, but they said they were busy with other projects unfortunately.

**Comment by adamcogen** [comment]
Hi Jeremy, 

It's been a long time, but in case you're still interested in this type of work, I made a new drum machine that supports live MIDI output. It's basically a remake of my old Python drum machine in JavaScript (so it runs in the browser), with a bunch of improvements and new features, and with a Cync-inspired click-and-drag user interface. 

You can check it out here if you like: 
- repo: https://github.com/adamcogen/drum-machine
- live demo: https://adamcogen.github.io/drum-machine/

**Comment by adamcogen** [comment]
Thanks for the ideas! 

I just finished up "version 1.0," which was to get the basic functionality of everything working with as nice a UI as I could, and also had some ideas for improvements that will require more work later.

Regarding your specific ideas:
- For stretch/swing, I included a unique way to make swing time feels. You can click and drag the grey vertical lines that notes snap to (on the bottom of each quantized row) to offset all the notes on that row, so that they sound ahead of or behind the beat. You can check out the yellow notes in the patterns from the "Tutorial" section in the "examples" dropdown for some examples of how to use that to make different swing feels. By alternating between normal and "shifted" notes, then changing how much of an offset the "shifted" notes have as much as you like, you can create your own swing feels.
- For note volumes, you can edit them manually by ctrl+clicking a note and moving the mouse up and down. You can also edit volumes for a whole row at a time using the volume slider on the left side of each row. But yeah, no randomization yet. That would be cool.
  - I included help text whenever you mouse over an interactive object, which shows up in the gray box at the bottom of the screen, and also shows any key shortcuts like the one for editing note volumes.
- There's no way to load in wavs yet, but you can do it really easily if you run it locally, just by replacing the sound files in the "assets/sounds" directory. There's some info in the README for running it locally.
- A pencil tool for fast note placement, and also selection mode for duplication and precisely editing of one or more notes at a time, would both be nice.
- An arranger would be nice, for making sequences that are more than one loop long.

I'm not a UI / frontend / design guy, so it was tough to find the best way to make all the features easy to find! At some point I might make a quick video showing how to use everything, or something like that, and link it from the page.

**Comment by jeremydeanw** [comment]
Another idea is having the ability to load in an actual wav drum break.  
https://www.youtube.com/@ArmandoDrumBreaks/videos
https://www.youtube.com/@drumbreakdetective9347 
and have it represented (maybe concatenatively?) via an internal database of synthetic drum parts...thinking like how the 808 was done with analog synthesis. 
then you could actually dissect rhythms into their fundamental elements (of clicks, tones, bass...etc), and then send em out to midi! (like you have)  
Thats a crazy idea though haha.  
I'll keep an eye on this, I can see myself using it for sure with a drag and drop arranger (thats what its called!) part at the bottom, and I love the ability to save the URL!
